// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh6d20qMhXx1Hge1-YQ9fSsZVDrmpUHyY',
    appId: '1:105721110299:web:de237b9b4d8d064c4d3dbe',
    messagingSenderId: '105721110299',
    projectId: 'twitt-don',
    authDomain: 'twitt-don.firebaseapp.com',
    databaseURL: 'https://twitt-don-default-rtdb.firebaseio.com',
    storageBucket: 'twitt-don.appspot.com',
    measurementId: 'G-SD0Z85E7S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACIGFUosPuztsaBfCion-68JxWaTwwF_k',
    appId: '1:105721110299:android:b9313a63d58c9d814d3dbe',
    messagingSenderId: '105721110299',
    projectId: 'twitt-don',
    databaseURL: 'https://twitt-don-default-rtdb.firebaseio.com',
    storageBucket: 'twitt-don.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARrhBCOKMAJHNVFV9qv1NWHEBM3amQmNU',
    appId: '1:105721110299:ios:8187a7095e8354914d3dbe',
    messagingSenderId: '105721110299',
    projectId: 'twitt-don',
    databaseURL: 'https://twitt-don-default-rtdb.firebaseio.com',
    storageBucket: 'twitt-don.appspot.com',
    iosBundleId: 'com.example.twitterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARrhBCOKMAJHNVFV9qv1NWHEBM3amQmNU',
    appId: '1:105721110299:ios:a6d6296ff3f2c2424d3dbe',
    messagingSenderId: '105721110299',
    projectId: 'twitt-don',
    databaseURL: 'https://twitt-don-default-rtdb.firebaseio.com',
    storageBucket: 'twitt-don.appspot.com',
    iosBundleId: 'com.example.twitterApp.RunnerTests',
  );
}
